
[Paths]

; Primer Log
Primer_Log = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.5 Job Log\3.5.0 Primer\Primer Log v3.xlsx"

; Job Log (for Ligation Layout)
Job_Log = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.5 Job Log\3.5 In-house Progress v11.xlsx"

; Fragments Log (IDT Order Summary for Ligation Layout)
Fragments_Log = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.5 Job Log\3.5.0 Primer\3.5.0.4 IDT Order Summary Log\Summary IDT Log v2.xlsx"

; Shipment and QC log file
Shipment_and_QC_Log = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.5 Job Log\3.5.4 DNA prep for shipment\Shipment and QC Log.xlsx"

; Sequencing files
Sorted_Sequencing_Files = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.6 QC\3.6.2 Sorted sequencing"
Reference_Sequences = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.6 QC\3.6.0 Reference files"

; --- Backup Vector Logger Paths ---
Gene_Invoicing_Db = B8. Gene Synthesis, "B8. Gene Synthesis\4.0 Invoicing and Shipping\4.1 Gene Invoicing\Gene Invoicing database.xlsx"
Vector_Storage_Dir = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.7 Storage & Inventory\3.7.1 Vector Storage"

; --- QC File Prep Paths ---
QC_Gel_Images = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.6 QC\3.6.7 QC gel images"
QC_Gel_Ladder = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.6 QC\3.6.7 QC gel images\Ladder.jpg"
QC_Output_Folder = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.6 QC\3.6.5 QC files received"

; --- SG Check Paths ---
SG_Check_Output = B8. Gene Synthesis, "B8. Gene Synthesis\3.0 In-House Gene\3.6 QC\3.6.3 Sg check"
