/**
 * Minimal GenBank (.gb) file emitter.
 *
 * The BioPython workflow writes GenBank files with `SeqIO.write(record, ...)`
 * using the `genbank` format. We produce the same output without depending
 * on a parser/emitter library — the format is text-based and the records
 * we emit are simple (LOCUS + FEATURES + ORIGIN, no full annotation set).
 *
 * Format reference: https://www.ncbi.nlm.nih.gov/Sitemap/samplerecord.html
 *   - Each line starts at column 0 except continuation lines (column 21 for
 *     FEATURES, column 11 for qualifiers).
 *   - The sequence in ORIGIN is wrapped at 60 bp with 10-bp group spacing.
 * - File ends with `//`.
 */

import { findSubsequenceLocation } from "./sequenceUtils.js";

const SEQ_WIDTH = 60;
const GROUP_SIZE = 10;

/**
 * Wrap a sequence into the canonical ORIGIN-block format:
 *   "  1 atcgatcgat cgATCGATCG ......  60"
 *     ^col 0-5: 6-char left pad, then group chunks of 10 bases.
 *     ^col 11-onwards: groups separated by a single space.
 */
function formatOrigin(seq) {
  const upper = seq.toUpperCase();
  const lines = [];
  for (let i = 0; i < upper.length; i += SEQ_WIDTH) {
    const slice = upper.slice(i, i + SEQ_WIDTH);
    const groups = [];
    for (let j = 0; j < slice.length; j += GROUP_SIZE) {
      groups.push(slice.slice(j, j + GROUP_SIZE).toLowerCase());
    }
    const pos = String(i + 1).padStart(9, " ");
    lines.push(`${pos} ${groups.join(" ")}`);
  }
  return lines.join("\n");
}

/**
 * Build the FEATURES block for an insert annotation.
 *
 * GenBank FEATURES syntax:
 *   <5 feature_name>  <21 qualifier_name=value
 *                      <21 qualifier_name=value
 *   <5 misc_feature   <21 /label="Insert"
 *                      <21 /note="Insert sequence"
 *
 * For wrap-around (insert straddles the linearization point), we emit two
 * misc_feature entries (one per fragment) instead of using CompoundLocation,
 * because GenBank parsers handle two adjacent fragments more reliably than
 * join() locations. This is a behavioural choice documented here.
 */
function formatFeatures({ wrap, start, end, seqLen, insertLen }) {
  if (!wrap) {
    return [
      "     misc_feature    1.." + insertLen,
      '                     /label="Insert"',
      '                     /note="Insert sequence"',
    ].join("\n");
  }
  // Wrap-around: two fragments.
  // First fragment: start..seqLen (length = seqLen - start)
  // Second fragment: 1..end (length = end)
  const frag1Len = seqLen - start;
  const frag2Len = end;
  return [
    `     misc_feature    ${start + 1}..${seqLen}`,
    '                     /label="Insert"',
    '                     /note="Insert sequence (wrap-around, fragment 1)"',
    `     misc_feature    1..${frag2Len}`,
    '                     /label="Insert"',
    '                     /note="Insert sequence (wrap-around, fragment 2)"',
  ].join("\n");
}

/**
 * Build a GenBank file string for a vector + optional insert annotation.
 *
 * @param {object} args
 * @param {string} args.jobid         - becomes LOCUS name and DEFINITION
 * @param {string} args.finalVector   - full vector sequence (raw, may include whitespace)
 * @param {string} [args.insertSeq]   - insert to annotate (optional)
 * @returns {{ ok: true, text: string } | { ok: false, error: string }}
 */
export function buildGenbank({ jobid, finalVector, insertSeq }) {
  const cleanVector = (finalVector || "").replace(/\s+/g, "");
  if (!cleanVector) {
    return { ok: false, error: "Empty Final Vector sequence" };
  }
  const len = cleanVector.length;
  const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
  const idStr = String(jobid || "").trim();
  const nameField = idStr.slice(0, 20).padEnd(20);

  const lines = [];
  // LOCUS line: 9 spaces pad + name(20 chars padded) + length + ' bp' + ' DNA' + '  circular' + ' SYN' + date
  lines.push(`LOCUS       ${nameField}${String(len).padStart(11, " ")} bp    DNA     circular  SYN ${today}`);
  // DEFINITION line.
  const def = `${idStr} exported by QC Vector Map Prep.`;
  lines.push(`DEFINITION  ${def}.`);
  lines.push("ACCESSION   ");
  lines.push("VERSION     ");
  lines.push("KEYWORDS    .");
  lines.push("SOURCE      synthetic construct");
  lines.push("  ORGANISM  synthetic construct");
  lines.push("            other sequences; artificial sequences.");
  lines.push("COMMENT     Generated by QC Vector Map Prep (BioPython workflow).");
  // FEATURES block (only if insert present + locatable)
  if (insertSeq && insertSeq.replace(/\s+/g, "")) {
    const loc = findSubsequenceLocation(cleanVector, insertSeq);
    if (!loc) {
      return { ok: false, error: "Insert sequence not found in Final Vector" };
    }
    lines.push("FEATURES             Location/Qualifiers");
    lines.push(
      formatFeatures({
        wrap: loc.wrap,
        start: loc.start,
        end: loc.end,
        seqLen: len,
        insertLen: insertSeq.replace(/\s+/g, "").length,
      })
    );
  }
  lines.push("ORIGIN");
  lines.push(formatOrigin(cleanVector));
  lines.push("//");
  lines.push("");

  return { ok: true, text: lines.join("\n") };
}
